GET {{hostname}}/posts
###

GET {{hostname}}/posts/6656fa9b6ab180780046bddc
###


POST {{hostname}}/posts

{
	"text": "Create post"
}
###

PUT {{hostname}}/posts/6656fa9b6ab180780046bddc

{
	"text": "Update post 1"
}

###

DELETE {{hostname}}/posts/6656fa9b6ab180780046bddc
