GET {{hostname}}/comments
###

GET {{hostname}}/comments/664c8ea4113d747f94596130
###


POST {{hostname}}/comments

{
	"text": "Create comments"
}
###

PUT {{hostname}}/comments/664c911c95df6f6c7a8575e2

{
	"text": "Update comments 1"
}

###

DELETE {{hostname}}/comments/664c911c95df6f6c7a8575e2
