GET {{hostname}}/comments
###

GET {{hostname}}/comments/6657025e57776e2ef8e742f8
###


POST {{hostname}}/comments/66581bde299a13710fbca376

{
	"text": "Create comments"
}
###

PUT {{hostname}}/comments/665818c6bbcbd7f5bc6b41d1

{
	"text": "Update comments 1"
}
 
###

DELETE {{hostname}}/comments/66581d19299a13710fbca390/66581bde299a13710fbca376
